#!/bin/sh

case $BLOCK_BUTTON in
    3) pamixer -t ;;
    4) pamixer -i 5 ;;
    5) pamixer -d 5 ;;
esac

print_block() {
    [[ $(pamixer --get-mute) = "true" ]] && echo 婢 && exit
    echo 墳 $(pamixer --get-volume-human);
}
print_block
