#!/bin/env bash

a=$(cat ~/.config/i3blocks/blockets/.openweather.key)

$(curl "https://api.openweathermap.org/data/2.5/weather?q=Cuiaba,br&units=metric&APPID=$a" -o /tmp/openweather)

echo $(jq '.main.temp, .main.feels_like, .main.humidity, .name' /tmp/openweather | tr '\n' ':' | awk -F: '{print $1"("$2")°C H: "$3"%/"$4}' | tr -d '"')
