#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d       VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Brave-browser  desktop='^2'  
bspc rule -a firefox        desktop='^2'  
bspc rule -a mpv            desktop='^4'  
bspc rule -a qBittorrent    desktop='^5'  
bspc rule -a Steam          desktop='^3'  
bspc rule -a Lutris         desktop='^3'  
bspc rule -a Anki           desktop='^6' state=floating

xsetroot -cursor_name left_ptr &
picom --xrender-sync-fence --no-fading-openclose &
nm-applet &
pgrep udiskie || udiskie  -t &
polybar -r &
nitrogen --restore &
